module Mannequin
  class Address
    attr_reader :street_address, :street_number, :street_name, :street_type, :city, :state, :state_code, :country
    
    def initialize
      # Set variables from functions
      street_number = generated_street_number
      street_name = generated_street_name
      street_type = generated_street_type
      street_address = "#{street_number} #{street_name} #{street_type}"
      city = generated_city
      state = generated_state
      country = generated_country
      
      
      # Initialize attributes
      @street_address = street_address
      @street_number = street_number
      @street_name = street_name
      @street_type = street_type
      @city = city
      @state = state[1]
      @state_code = state[0]
      @country = country
    end
    
    private
    
    def generated_street_number
      array_of_street_numbers = (1..2000).to_a
      return array_of_street_numbers.sample.to_s
    end
    
    def generated_street_name
      array_of_street_names = ["Maple", "Oak", "Poplar", "Cherry", "Dogwood"]
      return array_of_street_names.sample
    end
    
    def generated_street_type
      array_of_street_types = ["St", "Rd", "Cir", "Ct", "Way", "Ave"]
      return array_of_street_types.sample
    end
    
    def generated_city
      array_of_cities = ["Beijing", "Bogota", "Buenos Aires", "Cairo", "Delhi", "Dhaka", "Guangzhou", "Istanbul", "Jakarta", "Karachi", "Kinshasa", "Kolkata", "Lagos", "Lima", "London", "Los Angeles", "Manila", "Mexico City", "Moscow", "Mumbai", "New York City", "Osaka", "Rio de Janeiro", "Sao Paulo", "Seoul", "Shanghai", "Shenzhen", "Tehran", "Tianjin", "Tokyo"]
      return array_of_cities.sample
    end
    
    def generated_state
      # List of states from https://gist.github.com/2991970
      array_of_states = [
        ["AK", "Alaska"], 
        ["AL", "Alabama"], 
        ["AR", "Arkansas"], 
        ["AS", "American Samoa"], 
        ["AZ", "Arizona"], 
        ["CA", "California"], 
        ["CO", "Colorado"], 
        ["CT", "Connecticut"], 
        ["DC", "District of Columbia"], 
        ["DE", "Delaware"], 
        ["FL", "Florida"], 
        ["GA", "Georgia"], 
        ["GU", "Guam"], 
        ["HI", "Hawaii"], 
        ["IA", "Iowa"], 
        ["ID", "Idaho"], 
        ["IL", "Illinois"], 
        ["IN", "Indiana"], 
        ["KS", "Kansas"], 
        ["KY", "Kentucky"], 
        ["LA", "Louisiana"], 
        ["MA", "Massachusetts"], 
        ["MD", "Maryland"], 
        ["ME", "Maine"], 
        ["MI", "Michigan"], 
        ["MN", "Minnesota"], 
        ["MO", "Missouri"], 
        ["MS", "Mississippi"], 
        ["MT", "Montana"], 
        ["NC", "North Carolina"], 
        ["ND", "North Dakota"], 
        ["NE", "Nebraska"], 
        ["NH", "New Hampshire"], 
        ["NJ", "New Jersey"], 
        ["NM", "New Mexico"], 
        ["NV", "Nevada"], 
        ["NY", "New York"], 
        ["OH", "Ohio"], 
        ["OK", "Oklahoma"], 
        ["OR", "Oregon"], 
        ["PA", "Pennsylvania"], 
        ["PR", "Puerto Rico"], 
        ["RI", "Rhode Island"], 
        ["SC", "South Carolina"], 
        ["SD", "South Dakota"], 
        ["TN", "Tennessee"], 
        ["TX", "Texas"], 
        ["UT", "Utah"], 
        ["VA", "Virginia"], 
        ["VI", "Virgin Islands"], 
        ["VT", "Vermont"], 
        ["WA", "Washington"], 
        ["WI", "Wisconsin"], 
        ["WV", "West Virginia"], 
        ["WY", "Wyoming"] 
      ]
      return array_of_states.sample
    end
    
    def generated_country
      # List of countries from https://gist.github.com/370774
      array_of_countries = [
        "Afghanistan",
        "Aland Islands",
        "Albania",
        "Algeria",
        "American Samoa",
        "Andorra",
        "Angola",
        "Anguilla",
        "Antarctica",
        "Antigua And Barbuda",
        "Argentina",
        "Armenia",
        "Aruba",
        "Australia",
        "Austria",
        "Azerbaijan",
        "Bahamas",
        "Bahrain",
        "Bangladesh",
        "Barbados",
        "Belarus",
        "Belgium",
        "Belize",
        "Benin",
        "Bermuda",
        "Bhutan",
        "Bolivia",
        "Bosnia and Herzegowina",
        "Botswana",
        "Bouvet Island",
        "Brazil",
        "British Indian Ocean Territory",
        "Brunei Darussalam",
        "Bulgaria",
        "Burkina Faso",
        "Burundi",
        "Cambodia",
        "Cameroon",
        "Canada",
        "Cape Verde",
        "Cayman Islands",
        "Central African Republic",
        "Chad",
        "Chile",
        "China",
        "Christmas Island",
        "Cocos (Keeling) Islands",
        "Colombia",
        "Comoros",
        "Congo",
        "Congo, the Democratic Republic of the",
        "Cook Islands",
        "Costa Rica",
        "Cote d'Ivoire",
        "Croatia",
        "Cuba",
        "Cyprus",
        "Czech Republic",
        "Denmark",
        "Djibouti",
        "Dominica",
        "Dominican Republic",
        "Ecuador",
        "Egypt",
        "El Salvador",
        "Equatorial Guinea",
        "Eritrea",
        "Estonia",
        "Ethiopia",
        "Falkland Islands (Malvinas)",
        "Faroe Islands",
        "Fiji",
        "Finland",
        "France",
        "French Guiana",
        "French Polynesia",
        "French Southern Territories",
        "Gabon",
        "Gambia",
        "Georgia",
        "Germany",
        "Ghana",
        "Gibraltar",
        "Greece",
        "Greenland",
        "Grenada",
        "Guadeloupe",
        "Guam",
        "Guatemala",
        "Guernsey",
        "Guinea",
        "Guinea-Bissau",
        "Guyana",
        "Haiti",
        "Heard and McDonald Islands",
        "Holy See (Vatican City State)",
        "Honduras",
        "Hong Kong",
        "Hungary",
        "Iceland",
        "India",
        "Indonesia",
        "Iran, Islamic Republic of",
        "Iraq",
        "Ireland",
        "Isle of Man",
        "Israel",
        "Italy",
        "Jamaica",
        "Japan",
        "Jersey",
        "Jordan",
        "Kazakhstan",
        "Kenya",
        "Kiribati",
        "Korea, Democratic People's Republic of",
        "Korea, Republic of",
        "Kuwait",
        "Kyrgyzstan",
        "Lao People's Democratic Republic",
        "Latvia",
        "Lebanon",
        "Lesotho",
        "Liberia",
        "Libyan Arab Jamahiriya",
        "Liechtenstein",
        "Lithuania",
        "Luxembourg",
        "Macao",
        "Macedonia, The Former Yugoslav Republic Of",
        "Madagascar",
        "Malawi",
        "Malaysia",
        "Maldives",
        "Mali",
        "Malta",
        "Marshall Islands",
        "Martinique",
        "Mauritania",
        "Mauritius",
        "Mayotte",
        "Mexico",
        "Micronesia, Federated States of",
        "Moldova, Republic of",
        "Monaco",
        "Mongolia",
        "Montenegro",
        "Montserrat",
        "Morocco",
        "Mozambique",
        "Myanmar",
        "Namibia",
        "Nauru",
        "Nepal",
        "Netherlands",
        "Netherlands Antilles",
        "New Caledonia",
        "New Zealand",
        "Nicaragua",
        "Niger",
        "Nigeria",
        "Niue",
        "Norfolk Island",
        "Northern Mariana Islands",
        "Norway",
        "Oman",
        "Pakistan",
        "Palau",
        "Palestinian Territory, Occupied",
        "Panama",
        "Papua New Guinea",
        "Paraguay",
        "Peru",
        "Philippines",
        "Pitcairn",
        "Poland",
        "Portugal",
        "Puerto Rico",
        "Qatar",
        "Reunion",
        "Romania",
        "Russian Federation",
        "Rwanda",
        "Saint Barthelemy",
        "Saint Helena",
        "Saint Kitts and Nevis",
        "Saint Lucia",
        "Saint Pierre and Miquelon",
        "Saint Vincent and the Grenadines",
        "Samoa",
        "San Marino",
        "Sao Tome and Principe",
        "Saudi Arabia",
        "Senegal",
        "Serbia",
        "Seychelles",
        "Sierra Leone",
        "Singapore",
        "Slovakia",
        "Slovenia",
        "Solomon Islands",
        "Somalia",
        "South Africa",
        "South Georgia and the South Sandwich Islands",
        "Spain",
        "Sri Lanka",
        "Sudan",
        "Suriname",
        "Svalbard and Jan Mayen",
        "Swaziland",
        "Sweden",
        "Switzerland",
        "Syrian Arab Republic",
        "Taiwan, Province of China",
        "Tajikistan",
        "Tanzania, United Republic of",
        "Thailand",
        "Timor-Leste",
        "Togo",
        "Tokelau",
        "Tonga",
        "Trinidad and Tobago",
        "Tunisia",
        "Turkey",
        "Turkmenistan",
        "Turks and Caicos Islands",
        "Tuvalu",
        "Uganda",
        "Ukraine",
        "United Arab Emirates",
        "United Kingdom",
        "United States",
        "United States Minor Outlying Islands",
        "Uruguay",
        "Uzbekistan",
        "Vanuatu",
        "Venezuela",
        "Viet Nam",
        "Virgin Islands, British",
        "Virgin Islands, U.S.",
        "Wallis and Futuna",
        "Western Sahara",
        "Yemen",
        "Zambia",
        "Zimbabwe"
      ]
      return array_of_countries.sample
    end
  end
end
